"""Regenerate CHECKSUMS.txt: SHA-256 over the inputs that determine every generated byte.

Generation is seed-deterministic, so the dataset is fixed by (profile, seed, rho, edges)
*plus* these files: the calibration targets and the tunable configuration. Pinning them
lets a reviewer confirm they are reproducing from the same inputs the paper used, without
shipping the multi-GB parquets. The generated data itself is verified downstream by the
content fingerprint (`python -m t9sim.fingerprint <output_dir>`).

Usage:  python scripts/make_checksums.py
"""
from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "CHECKSUMS.txt"

# reproducibility-critical inputs, in read order
PATTERNS = ["calibration/*.csv", "config/*.yaml", "requirements.txt", "pyproject.toml"]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> None:
    files: list[Path] = []
    for pat in PATTERNS:
        files.extend(sorted(ROOT.glob(pat)))

    lines = [
        "# T9 simulator - SHA-256 of the reproducibility-critical inputs.",
        "#",
        "# These files fix the generated dataset together with (profile, seed, rho, edges).",
        "# Verify:   sha256sum -c CHECKSUMS.txt        (Linux/macOS)",
        "#           python scripts/make_checksums.py  then diff against this file",
        "#",
        "# Generated data is not listed here - it is verified by content fingerprint:",
        "#           python -m t9sim.fingerprint <output_dir>",
        "",
    ]
    for f in files:
        rel = f.relative_to(ROOT).as_posix()
        lines.append(f"{sha256(f)}  {rel}")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(files)} files")


if __name__ == "__main__":
    main()
